# Generated by Django 5.1.15 on 2026-05-07 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(blank=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('expected_output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField()),
                ('output_tokens', models.PositiveIntegerField()),
                ('total_tokens', models.PositiveIntegerField()),
                ('input_cost', models.DecimalField(decimal_places=8, max_digits=14)),
                ('output_cost', models.DecimalField(decimal_places=8, max_digits=14)),
                ('estimated_cost', models.DecimalField(decimal_places=8, max_digits=14)),
                ('strategy', models.CharField(max_length=64)),
                ('input_price_at_estimate', models.DecimalField(decimal_places=8, max_digits=12)),
                ('output_price_at_estimate', models.DecimalField(decimal_places=8, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='providers.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='tokenizer_e_user_id_15b42b_idx'), models.Index(fields=['model', '-created_at'], name='tokenizer_e_model_i_5e6e50_idx')],
            },
        ),
    ]
