# Generated by Django 5.1.15 on 2026-05-07 04:34

import apps.providers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL-safe identifier (e.g. 'openai', 'anthropic', 'google').", max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['slug'], name='providers_p_slug_b5b7d2_idx'), models.Index(fields=['is_active'], name='providers_p_is_acti_7dfa8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='URL-safe identifier, unique per provider.', max_length=150)),
                ('input_price', models.DecimalField(decimal_places=8, help_text='USD per 1,000 input tokens.', max_digits=12)),
                ('output_price', models.DecimalField(decimal_places=8, help_text='USD per 1,000 output tokens.', max_digits=12)),
                ('context_window', models.PositiveIntegerField(help_text='Maximum total tokens (input + output).')),
                ('max_output_tokens', models.PositiveIntegerField(help_text='Maximum tokens the model can generate in one response.')),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='List of capability codes (see Capability choices).', validators=[apps.providers.models.validate_capabilities])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='providers.provider')),
            ],
            options={
                'ordering': ('provider__name', 'name'),
                'indexes': [models.Index(fields=['provider', 'is_active'], name='providers_a_provide_827651_idx'), models.Index(fields=['slug'], name='providers_a_slug_35f0ef_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'slug'), name='uq_aimodel_provider_slug'), models.CheckConstraint(condition=models.Q(('input_price__gte', 0)), name='ck_aimodel_input_price_nonneg'), models.CheckConstraint(condition=models.Q(('output_price__gte', 0)), name='ck_aimodel_output_price_nonneg'), models.CheckConstraint(condition=models.Q(('max_output_tokens__lte', models.F('context_window'))), name='ck_aimodel_max_out_le_ctx')],
            },
        ),
    ]
