# Generated by Django 5.1.15 on 2026-05-07 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=16)),
                ('cap_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold_50', models.BooleanField(default=True)),
                ('threshold_80', models.BooleanField(default=True)),
                ('threshold_100', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_model', models.ForeignKey(blank=True, help_text='Limit this budget to a single model. Leave empty for all models.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='providers.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_pct', models.PositiveSmallIntegerField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('actual_cost_usd', models.DecimalField(decimal_places=8, max_digits=14)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgets.budget')),
            ],
            options={
                'ordering': ('-triggered_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('budget_alert', 'Budget Alert'), ('quota_warning', 'Quota Warning'), ('system', 'System')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'is_active'], name='budgets_bud_user_id_cec771_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('cap_usd__gt', 0)), name='ck_budget_cap_positive'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['budget', '-triggered_at'], name='budgets_bud_budget__b4d58f_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetalert',
            constraint=models.UniqueConstraint(fields=('budget', 'threshold_pct', 'period_start'), name='uq_budget_alert_period_threshold'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='budgets_not_user_id_0acc17_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='budgets_not_user_id_c97312_idx'),
        ),
    ]
